---
title: "git_01"
author: "Junior Cruz"
date: "Summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves
      
Did gyre and gimble in the wabe:

All mimsy were the borogoves,
      
And the mome raths outgrabe.

“Beware the Jabberwock, my son!

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

In shadows draped, I linger, silent, still,

Beneath the veiled embrace of twilight's chill,

Time's whispers echo in the hush of night,

As stars dance softly, weaving dreams in flight.

With bated breath, I wait upon the hour,

In quiet solitude, 'neath Luna's power,

Each heartbeat counts the moments passing by,

In this suspended realm where dreams can fly.

Through winding paths where patience finds its way,

I tread with hope, as dawn replaces gray,

A symphony of patience fills the air,

As waiting souls find solace in despair.

Yet in the waiting, blossoms grace the bough,

As seeds of longing find their way, somehow,

For in the quiet space where time abides,

New beginnings stir beneath the tides.

So let me wait, amidst the ebb and flow,

For destiny to carve its path, aglow,

In patience' embrace, I find my peace,

As waiting whispers secrets, sweet release.